name: Build

on:
  push:
    branches:
      - main
      - devel
  pull_request:
    branches:
      - main
      - devel

jobs:
  build:
    name: Verification
    runs-on: ubuntu-latest

    steps:
      - name: Clone
        uses: actions/checkout@v2

      - name: Run docker compose
        run: docker compose up -d --build

      - name: Wait building
        run: sleep 5 

      - name: Closing containers
        if: always()
        run: docker compose down
